const express = require('express');
const { authenticateUser, authenticateAdmin } = require('../middleware/authMiddleware');
const asyncHandler = require('../middleware/asyncHandler');
const { createBookingRequest, listBookingRequests, listAdminBookingRequests, updateBookingRequest, acceptQuote } = require('../controllers/flightController');
const router = express.Router();
router.post('/bookings', authenticateUser, asyncHandler(createBookingRequest));
router.get('/bookings', authenticateUser, asyncHandler(listBookingRequests));
router.post('/bookings/:reference/accept-quote', authenticateUser, asyncHandler(acceptQuote));
router.get('/admin/bookings', authenticateAdmin, asyncHandler(listAdminBookingRequests));
router.patch('/admin/bookings/:reference', authenticateAdmin, asyncHandler(updateBookingRequest));
module.exports = router;
