import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/header'
import Footer from './components/footer'
import { ThemeProvider } from './dashboard/Context/ThemeContext'
import { UserProvider } from './dashboard/Context/UserContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SubHub247',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider >

        <ThemeProvider >

        {/* <Header /> */}
        {children}
        {/* <Footer/> */}
        </ThemeProvider>
        </UserProvider>
        </body>
    </html>
  )
}
